# Generated by Django 3.2.6 on 2021-12-28 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Big_Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_id', models.PositiveIntegerField(unique=True)),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Big_Bosses',
            },
        ),
        migrations.CreateModel(
            name='CompanyLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'CompanyLevels',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('employment_date', models.DateField()),
                ('salary', models.PositiveIntegerField(blank=True)),
                ('salary_paid', models.PositiveIntegerField(null=True)),
                ('boss_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_boss_id', to='api.big_boss')),
                ('company_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.companylevels')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empl_position', to='api.position')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
